site_name: Python by Example
repo_url: https://github.com/braboj/tutorial-python
site_dir: site
docs_dir: docs

theme:
  name: readthedocs
  collapse_navigation: true

plugins:
  - search
  - awesome-pages

nav:
  - Language:
    - Introduction: A01_introduction.md
    - Variables: A02_variables.md
    - Comments: A03_comments.md
    - Operators: A04_operators.md
    - User Input: A05_user_input.md
    - Strings: A06_strings.md
    - Control Flow: A07_control_flow.md
    - Functions: A08_functions.md
    - Classes: A09_classes.md
    - Modules: A10_modules.md

  - Design:
    - OOP Basics: B01_oop_pillars.md
    - SOLID Principles: B02_solid_principles.md
    - Design Patterns: B03_design_patterns.md
    - Secure Design: B04_secure_design.md

  - Libraries:
    - Logging: C01_logging.md
    - Serialization: C12_serialization.md
    - Data Structures: C13_data_structures.md
