site_name: Python by Example
repo_url: https://github.com/braboj/tutorial-python
site_dir: site
docs_dir: docs

theme:
  name: readthedocs
  collapse_navigation: true

plugins:
  - search
  - awesome-pages

nav:
  - Project:
      - Home: index.md

  - Language:
    - Introduction: A01_introduction.md

  - Design:
    - OOP Basics: B01_oop_pillars.md

  - Libraries:
    - Logging: C01_logging.md
