site_name: Python by Example
repo_url: https://github.com/braboj/tutorial-python
site_dir: site
docs_dir: docs

theme:
  name: readthedocs
  collapse_navigation: true

plugins:
  - search
  - awesome-pages

nav:
  - Project:
      - Home: index.md

  - Examples:
    - Introduction: 01_introduction.md
    - Variables: 02_variables.md
    - Comments: 03_comments.md
    - Operators: 04_operators.md
    - User Input: 05_user_input.md
    - Control Flow: 07_control_flow.md
    - Functions: 08_functions.md
    - Classes: 09_classes.md
